[package]
name = "sigil-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
argon2 = { workspace = true }
chacha20poly1305 = { workspace = true }
aes-gcm = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
blake3 = { workspace = true }
hmac = { workspace = true }
sha1 = { workspace = true }

zeroize = { workspace = true }
secrecy = { workspace = true }
subtle = { workspace = true }

serde = { workspace = true }
serde_cbor = { workspace = true }
uuid = { workspace = true }

getrandom = { workspace = true }
rand = { workspace = true }

thiserror = { workspace = true }
base32 = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
hex-literal = "0.4"
rand_chacha = "0.3"

[features]
post-quantum = ["dep:ml-kem"]

[dependencies.ml-kem]
workspace = true
optional = true
